Basic Exercise feature
cesko-digital/movapp-android pull request #76
Opened 2023-09-10 19:48 UTC by Crustus

2023-09-15 05:24 UTC, vchlum commented
Hi @Crustus ! Thank you! Could you please rebase to resolve the conflict with ec26be6e11b3c1a902ec11367f36227c9643effd ? Also, It would be nice to add the translations of strings before merging.

2023-09-26 13:38 UTC, Rimusolamus requested changes

2023-09-26 13:38 UTC, Rimusolamus commented on app/src/main/java/cz/movapp/app/data/DictionaryDatasource.kt
> +        var dict = mutableListOf<DictionaryMetaCategoryData>()
val

2023-09-26 13:38 UTC, Rimusolamus commented on app/src/main/java/cz/movapp/app/data/DictionaryDatasource.kt
> +            ioException.printStackTrace()
shouldn't we show some error msg for the user in this case instead of crashing the app?

2023-09-26 13:38 UTC, Rimusolamus commented on app/src/main/java/cz/movapp/app/data/DictionaryDatasource.kt
> +        val jsonArr = JSONObject(jsonString).getJSONArray("categories")
We can serialize JSON using gson. Here is an example: https://www.myandroidsolutions.com/2019/07/25/android-parse-json-file-from-assets/

2023-09-26 13:38 UTC, Rimusolamus commented on app/src/main/java/cz/movapp/app/ui/exercise/ExerciseConfig.kt
> +val levels = arrayOf(
Could you leave a comment here on what these magic numbers mean? Mb we can have it as a constants?

2023-09-26 13:38 UTC, Rimusolamus commented on app/src/main/java/cz/movapp/app/ui/exercise/ExerciseViewModel.kt
> +                //Timber.d("section: $section")
Let's keep production code free of commented code

2023-09-26 13:38 UTC, Rimusolamus commented on app/src/main/java/cz/movapp/app/ui/exercise/ExerciseViewModel.kt
> +        return AnswerState.WRONG
probably it can be in the else branch?

2023-09-26 13:38 UTC, Rimusolamus commented on app/src/main/java/cz/movapp/app/ui/exercise/ExerciseViewModel.kt
> +        val sections = DictionaryDatasource.loadSections(App.ctx, LanguagePair.getDefault())
Let's avoid using Contex from the App. As it's a memory leak to hold and use context out of the static field.

2023-09-26 13:38 UTC, Rimusolamus commented on app/src/main/java/cz/movapp/app/ui/exercise/play/ExercisePlayAdapter.kt
> +        notifyDataSetChanged()
you could use methods like notifyItemChanged(int), notifyItemInserted(int),  notifyItemRemoved(int)
To get away with this you could use https://developer.android.com/reference/androidx/recyclerview/widget/DiffUtil

2023-09-26 13:38 UTC, Rimusolamus commented on app/src/main/java/cz/movapp/app/ui/exercise/play/ExercisePlayFragment.kt
> +                    binding.next.visibility = View.GONE
binding.next.isVisible = false
IMO looks better :)

2023-09-26 13:38 UTC, Rimusolamus commented on app/src/main/java/cz/movapp/app/ui/exercise/play/ExercisePlayFragment.kt
> +                    exerciseViewModel.playLocalSound(requireContext(), answer.id, 0.75f)
let's extract this number and place it somewhere at the top of the class as a constant with a comment about what this number means

2023-09-26 13:38 UTC, Rimusolamus commented on app/src/main/java/cz/movapp/app/ui/exercise/setup/ExerciseSetupAdapter.kt
> +    ) : RecyclerView.ViewHolder(binding.root) {
redundant class body

2023-09-26 13:38 UTC, Rimusolamus commented on app/src/main/res/layout/exercise_audio_item.xml
> +    xmlns:app="http://schemas.android.com/apk/res-auto"
can be removed

2023-09-26 13:38 UTC, Rimusolamus commented on app/src/main/res/layout/exercise_audio_item.xml
> +    <ImageView
add content description pls

2023-09-26 13:38 UTC, Rimusolamus commented on app/src/main/res/layout/exercise_play_item.xml
> +    android:foreground="?attr/selectableItemBackground"
Attribute android:foreground has no effect on API levels lower than 23 (current min is 21)
damn why we still support API 21 :D

2023-09-26 13:38 UTC, Rimusolamus commented on app/src/main/res/layout/exercise_setup_item.xml
> +    android:foreground="?attr/selectableItemBackground"
same

2023-09-26 13:38 UTC, Rimusolamus commented on app/src/main/res/layout/exercise_setup_item.xml
> +    android:foreground="?attr/selectableItemBackground"
@vchlum is there a reason why we support API 21? Almost nobody supports this old version of Android. I'd suggest bumping it at least to 23, better to 24 or 26.

2023-09-26 13:38 UTC, Rimusolamus commented on app/src/main/res/layout/fragment_exercise_play.xml
> +            <ImageView
contentDescription pls

2023-09-26 13:38 UTC, Rimusolamus commented on app/src/main/res/layout/fragment_exercise_setup.xml
> +            android:text="1"
Hardcoded string, should use @string resource

2023-09-26 13:38 UTC, Rimusolamus commented on app/src/main/res/layout/fragment_exercise_setup.xml
> +            android:text="5"
Hardcoded string, should use @string resource

2023-09-26 13:38 UTC, Rimusolamus commented on app/src/main/res/layout/fragment_exercise_setup.xml
> +            android:text="10"
Hardcoded string, should use @string resource

2023-09-28 09:20 UTC, rade2k commented on app/src/main/java/cz/movapp/app/ui/children/ChildrenFairyTalesAdapter.kt
> +            it.first.supportedLanguages.contains(langPair.from.langCode)
langPair.to.langCode?

2023-09-28 09:45 UTC, rade2k commented on app/src/main/java/cz/movapp/app/ui/exercise/setup/ExerciseSetupFragment.kt
> +            if (BuildConfig.DEBUG) {
Myslím, že to není třeba obalovat tím ifem. V App.kt je už podmínka debug modu vyřešená.

2023-09-28 09:49 UTC, rade2k requested changes
Pár věcí k opravě.

2023-10-09 21:05 UTC, merged